package com.nhlstenden;

/**
 * This class has a few static Strings which are all the regex' used in the whole parser
 */
public class Regex {

    public static String moviesRegex = "\\\"?(?<title>.*?)\\\"?\\s\\((?<year>\\d{4}|(?<unknownYear>[?]{4}))(?:\\/(?<movieNamePerYear>.*?))?\\)\\s?(?:\\{(?:(?<seriesEpisodeName>.*?)\\s?)(?:\\(\\#(?<seriesSeason>\\d{1,})\\.(?<seriesEpisode>\\d{1,})\\))?\\})?(?:\\((?<mediaType>.{1,2})\\))?(?:\\s+(?<seriesPeriod>(?<startYear>[\\d]{4})\\-(?<endYear>[\\d]{4}|[?]{4})))?(?:\\s\\{(?<suspended>.*\\}))?(?:\\s+(?<yearOfRelease>[\\d]{4}|[?]{4})?)";

    public static String ratingsRegex = "\\s{6}(?<distribution>.{1,10})\\s+(?<votes>\\d{1,7})\\s{2,3}(?<rank>\\d{1,2}\\.\\d)\\s{2}(?:\\\"?(?<title>.*?)\\\"?)\\s\\((?<year>\\d{4}|(?<unknownYear>[?]{4}))(?:\\/(?<movieNamePerYear>.*?)?)?\\)(?:\\s\\{(?:(?<seriesEpisodeName>.*?)\\s?)(?:\\(\\#(?<seriesSeason>\\d{1,})\\.(?<seriesEpisode>\\d{1,})\\))?\\})?(?:\\s\\((?<mediaType>\\w{1,})\\))?";

    public static String runningTimeRegex = "\\\"?(?<title>.*?)\\\"?\\s\\((?<year>\\d{4}|(?<unknownYear>[?]{4}))\\)?(?:\\/(?<movieNamePerYear>.*?)\\))?\\s+(?:\\{(?!\\{)(?:(?<seriesEpisodeName>.*?)\\s?)(?:\\(\\#(?<seriesSeason>\\d{1,})\\.(?<seriesEpisode>\\d{1,})\\))?\\})?\\s?(?:\\((?<mediatype>.{1,2})\\))?\\s?(?:\\{\\{(?<suspended>.*?)\\}\\})?\\s*(?:(?<time>\\d{1,}))?(?:(?<country>.*?)\\:(?:.*?(?<countryTime>\\d{1,})))?(?:(?<extraInformation>.*))?";

    public static String businessRegex = "(?:(?<MV>MV):\\s(?<mvTitle>.*?)\\s+?\\((?<mvYear>\\d{4}|(?<unknownYear>[?]{4}))(?:\\/(?<movieNamePerYear>.*?))?\\)\\s(?:\\{(?!\\{)(?:(?<seriesEpisodeName>.*?)\\s?)(?:\\(\\#(?<seriesSeason>\\d{1,})\\.(?<seriesEpisode>\\d{1,})\\))?\\})?(?:\\((?<mediatype>.{1,2})\\))?(?:\\{\\{(?<suspended>.*?)\\}\\})?)?(?:(?<AD>AD):\\s(?<adAmount>[\\d,.]*)\\s\\((?<adCountry>\\w*)\\)\\s(?:\\s*?\\((?:(?<adDay>\\d{1,2}))?\\s?(?:(?<adMonths>[A-z]{1,}))?\\s?(?:(?<adYear>\\d{4}))?\\))?(?:\\s\\((?<adScreens>[\\d,]*\\s\\w*)\\))?)?(?:(?<BT>BT):\\s(?<btCurrency>\\w{1,})\\s(?<btAmount>[\\d,]*) )?(?:(?<CP>CP):\\s(?<copyrightHolder>.*) )?(?:(?<GR>GR):\\s(?<grCurrency>\\w{1,})\\s(?<grAmount>[\\d,.]*)\\s\\((?<grInitials>.*?)\\)(?:\\s\\((?:(?<grDay>\\d{1,2}))?\\s(?:(?<grMonths>[A-z]{1,}))?\\s(?:(?<grYear>\\d{4}))?\\))?\\s(?:\\((?<grExtraInfo>.*)\\))?)?(?:(?<OW>OW):\\s(?<owCurrency>\\w{1,})\\s(?<owAmount>[\\d,.]*)\\s(?:\\s*?\\((?<owInitials>[A-z]*)\\))?(?:\\s*?\\((?:(?<owDay>\\d{1,2}))?\\s?(?:(?<owMonths>[A-z]{1,}))?\\s?(?:(?<owYear>\\d{4}))?\\))?(?:\\s\\((?<owScreens>[\\d,]*\\s\\w*)\\))?\\s?(?:\\((?<owExtraInfo>.*)\\)))?(?:(?<PD>PD):\\s(?:(?<pdStartDay>\\d{1,2}))?\\s?(?:(?<pdStartMonths>[A-z]{1,}))?\\s?(?:(?<pdStartYear>\\d{4}))?\\s?-\\s?(?:(?<pdEndDay>\\d{1,2}))?\\s?(?:(?<pdEndMonths>[A-z]{1,}))?\\s?(?:(?<pdEndYear>\\d{4}))?)?(?:(?<SD>SD):\\s(?:(?<sdStartDay>\\d{1,2}))?\\s?(?:(?<sdStartMonths>[A-z]{1,}))?\\s?(?:(?<sdStartYear>\\d{4}))?\\s?-\\s?(?:(?<sdEndDay>\\d{1,2}))?\\s?(?:(?<sdEndMonths>[A-z]{1,}))?\\s?(?:(?<sdEndYear>\\d{4}))?\\s?(?:\\((?<sdExtraInfo>.*)\\))?)?(?:(?<RT>RT):\\s(?<rtCurrency>\\w{1,})\\s(?<rtAmount>[\\d,.]*)\\s(?:\\((?<USA>.*)\\))?\\s(?:\\((?<rtExtraInfo>.*)\\))?)?(?:(?<WG>WG):\\s(?<wgCurrency>\\w{1,})\\s(?<wgAmount>[\\d,.]*)\\s(?:\\s*?\\((?<wgInitials>[A-z]*)\\))?(?:\\s*?\\((?:(?<wgDay>\\d{1,2}))?\\s?(?:(?<wgMonths>[A-z]{1,}))?\\s?(?:(?<wgYear>\\d{4}))?\\))?(?:\\s\\((?<wgScreens>[\\d,]*\\s\\w*)\\))?)?(?<trash>\\-{79}?)?";

    public static String genreRegex = "^\\\"?(?<title>.*?)\\\"?\\s\\((?<year>\\d{4}|(?<unknownYear>[?]{4}))\\)?(?:\\/(?<movieNamePerYear>.*?)\\))?(?:\\s\\{(?!\\{)(?:(?<seriesEpisodeName>.*?)\\s?)(?:\\(\\#(?<seriesSeason>\\d{1,})\\.(?<seriesEpisode>\\d{1,})\\))?\\})?\\s?(?:\\((?<mediatype>.{1,2})\\))?\\s?(?:\\{\\{(?<suspended>.*?)\\}\\})?(?:(?!\\{.*?\\(\\#)\\{.*\\})?\\t*(?<genre>.*)$";

    public static String locationRegex = "^\\\"?(?<title>.*?)\\\"?\\s\\((?<year>\\d{4}|(?<unknownYear>[?]{4}))(?:\\/(?<movieNamePerYear>.*?)?)?\\)(?:\\s\\{(?!\\{)(?:(?<seriesEpisodeName>.*?)\\s?)(?:\\(\\#(?<seriesSeason>\\d{1,})\\.(?<seriesEpisode>\\d{1,})\\))?\\})?\\s?(?:\\((?<mediatype>.{1,2})\\))?\\s?(?:\\{\\{(?<suspended>.*?)\\}\\})?\\t+(?:(?<locationInfo1>.*?))?(?:,\\s(?<locationInfo2>.*?))?(?:,\\s(?<locationInfo3>.*?))?(?:,\\s(?<locationInfo4>.*?))?(?:,\\s(?<locationInfo5>.*?))?(?:,\\s(?<locationInfo6>.*?))?(?:\\t\\((?<extraInfo>.*)\\))?$";

    public static String actorRegex = "^(?:(?<lastName>.*?),\\s)?(?<firstName>.*?)\\t+\\\"?(?<title>.*?)\\\"?\\s\\((?<year>\\d{4}|(?<unknownYear>[?]{4}))(?:\\/(?<movieNamePerYear>.*?)?)?\\)\\s?(?:\\{(?:(?<seriesEpisodeName>.*?)\\s?)(?:\\(\\#(?<seriesSeason>\\d{1,})\\.(?<seriesEpisode>\\d{1,})\\))?\\})?\\s*?(?:\\((?<mediaType>\\w{1,3})\\))?\\s*?(?:\\((?:as)?\\s?(?<actorFunction>.*)\\))?\\s*(?:\\[(?<characterName>.*)\\])?\\s*(?:\\<(\\d*)\\>)?$";

}
